# Generated by Django 5.0.6 on 2024-07-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stickynote',
            old_name='description',
            new_name='content',
        ),
    ]
